from enum import Enum
from pynput.keyboard import Key

class KeySet(Enum):
    POWER = [Key.tab]
    RECORD = ['v']
    PAUSE = ['p']
    SNAPSHOT = ['c']
    RAISE = ['e']
    LOWER = ['q']
    MOVE_FORWARD = ['w']
    MOVE_BACKWARD = ['s']
    MOVE_LEFT = ['a']
    MOVE_RIGHT = ['d']
    ZOOM_IN = ['z']
    ZOOM_OUT = ['x']
    LEVEL_OUT = [Key.shift, 's']
    ROTATE_LEFT = [Key.shift, 'a']
    ROTATE_RIGHT = [Key.shift, 'd']
    TURN_LEFT = [',']
    TURN_RIGHT = ['.']
    MOVE_TO_POSITION_5 = ['5']
    MOVE_TO_POSITION_6 = ['6']
    MOVE_TO_POSITION_7 = ['7']
    MOVE_TO_POSITION_8 = ['8']
    MOVE_TO_POSITION_9 = ['9']
    SNAP_TO_POSITION_5 = [Key.shift, '5']
    SNAP_TO_POSITION_6 = [Key.shift, '6']
    SNAP_TO_POSITION_7 = [Key.shift, '7']
    SNAP_TO_POSITION_8 = [Key.shift, '8']
    SNAP_TO_POSITION_9 = [Key.shift, '9']